targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: graphql_api_test|lib/schema.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: 'package:http/http.dart'
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: graphql_api_test|lib/schema.graphql
          custom_serializers:
            - import: 'package:graphql_api_test/upload_serializer.dart'
              name: UploadSerializer